// <auto-generated />
using System;
using BestelBuddy.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BestelBuddy.Migrations
{
    [DbContext(typeof(BestelBuddyContext))]
    partial class BestelBuddyContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("BestelBuddy.Models.Bestelling", b =>
                {
                    b.Property<int>("BestellingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BezoekerId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Tijdstip")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TijdstipKlaar")
                        .HasColumnType("TEXT");

                    b.Property<double>("TotaalBedrag")
                        .HasColumnType("REAL");

                    b.HasKey("BestellingId");

                    b.HasIndex("BezoekerId");

                    b.ToTable("Bestellingen");
                });

            modelBuilder.Entity("BestelBuddy.Models.Bezoeker", b =>
                {
                    b.Property<int>("BezoekerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("EmailAdres")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("BezoekerId");

                    b.ToTable("Bezoekers");
                });

            modelBuilder.Entity("BestelBuddy.Models.Evenement", b =>
                {
                    b.Property<int>("EvenementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("TEXT");

                    b.Property<string>("Locatie")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("EvenementId");

                    b.ToTable("Evenementen");
                });

            modelBuilder.Entity("BestelBuddy.Models.Foodtruck", b =>
                {
                    b.Property<int>("FoodtruckId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EvenementId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsBeschikbaar")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MenuKaartId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Specialiteit")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("FoodtruckId");

                    b.HasIndex("EvenementId");

                    b.HasIndex("MenuKaartId");

                    b.ToTable("Foodtrucks");
                });

            modelBuilder.Entity("BestelBuddy.Models.Medewerker", b =>
                {
                    b.Property<int>("MedewerkerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FoodtruckId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("MedewerkerId");

                    b.HasIndex("FoodtruckId");

                    b.ToTable("Medewerkers");
                });

            modelBuilder.Entity("BestelBuddy.Models.MenuItem", b =>
                {
                    b.Property<int>("MenuItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BestellingId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MenuKaartId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Prijs")
                        .HasColumnType("REAL");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("MenuItemId");

                    b.HasIndex("BestellingId");

                    b.HasIndex("MenuKaartId");

                    b.ToTable("MenuItems");
                });

            modelBuilder.Entity("BestelBuddy.Models.MenuKaart", b =>
                {
                    b.Property<int>("MenuKaartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.HasKey("MenuKaartId");

                    b.ToTable("MenuKaarten");
                });

            modelBuilder.Entity("BestelBuddy.Models.Planner", b =>
                {
                    b.Property<int>("PlannerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("EmailAdres")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("PlannerId");

                    b.ToTable("Planners");
                });

            modelBuilder.Entity("BestelBuddy.Models.Bestelling", b =>
                {
                    b.HasOne("BestelBuddy.Models.Bezoeker", null)
                        .WithMany("Bestellingen")
                        .HasForeignKey("BezoekerId");
                });

            modelBuilder.Entity("BestelBuddy.Models.Foodtruck", b =>
                {
                    b.HasOne("BestelBuddy.Models.Evenement", null)
                        .WithMany("Foodtrucks")
                        .HasForeignKey("EvenementId");

                    b.HasOne("BestelBuddy.Models.MenuKaart", "Menukaart")
                        .WithMany()
                        .HasForeignKey("MenuKaartId");

                    b.Navigation("Menukaart");
                });

            modelBuilder.Entity("BestelBuddy.Models.Medewerker", b =>
                {
                    b.HasOne("BestelBuddy.Models.Foodtruck", null)
                        .WithMany("Medewerkers")
                        .HasForeignKey("FoodtruckId");
                });

            modelBuilder.Entity("BestelBuddy.Models.MenuItem", b =>
                {
                    b.HasOne("BestelBuddy.Models.Bestelling", null)
                        .WithMany("Items")
                        .HasForeignKey("BestellingId");

                    b.HasOne("BestelBuddy.Models.MenuKaart", null)
                        .WithMany("Items")
                        .HasForeignKey("MenuKaartId");
                });

            modelBuilder.Entity("BestelBuddy.Models.Bestelling", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("BestelBuddy.Models.Bezoeker", b =>
                {
                    b.Navigation("Bestellingen");
                });

            modelBuilder.Entity("BestelBuddy.Models.Evenement", b =>
                {
                    b.Navigation("Foodtrucks");
                });

            modelBuilder.Entity("BestelBuddy.Models.Foodtruck", b =>
                {
                    b.Navigation("Medewerkers");
                });

            modelBuilder.Entity("BestelBuddy.Models.MenuKaart", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
